package GymInterface;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
public class Encryption {
	public static String Encrypt(String strMsg){
		String strEncrypted="";
		int intCtr=0;
		char ArrChar[] = new char[strMsg.length()];
		for(intCtr=0;intCtr<strMsg.length();intCtr++){
			ArrChar[intCtr]=strMsg.charAt(intCtr);
		}
		for(intCtr=0;intCtr<strMsg.length();intCtr++){
			switch(ArrChar[intCtr]){
			case 'A': strEncrypted+="XyZdjfd" +"@";
			break;
			case 'a': strEncrypted+="yJdEwHr" +"@";
			break;
			case 'B': strEncrypted+="1ayFBs2*" +"@";
			break;
			case 'b': strEncrypted+="xYd0221" +"@";
			break;
			case 'C': strEncrypted+="3fjks32" +"@";
			break;
			case 'c': strEncrypted+="fsjkhfj" +"@";
			break;
			case 'D': strEncrypted+="atsd7f66f" +"@";
			break;
			case 'd': strEncrypted+="dhfjshfjdf" +"@";
			break;
			case 'E': strEncrypted+="we67r5f62" +"@";
			break;
			case 'e': strEncrypted+=" 627s" +"@";
			break;
			case 'F': strEncrypted+="23yu23a" +"@";
			break;
			case 'f': strEncrypted+="fjsdhf7" +"@";
			break;
			case 'G': strEncrypted+="2ui2u4" +"@";
			break;
			case 'g': strEncrypted+="asdsd21" +"@";
			break;
			case 'H': strEncrypted+="fuef62" +"@";
			break;
			case 'h': strEncrypted+="4376fda" +"@";
			break;
			case 'I': strEncrypted+="djhs5AS" +"@";
			break;
			case 'i': strEncrypted+="dgshdg25" +"@";
			break;
			case 'J': strEncrypted+="xtte212" +"@";
			break;
			case 'j': strEncrypted+="y23sjoHr" +"@";
			break;
			case 'K': strEncrypted+="23241" +"@";
			break;
			case 'k': strEncrypted+="dhs621" +"@";
			break;
			case 'L': strEncrypted+="dhsd623" +"@";
			break;
			case 'l': strEncrypted+="dshdhs2" +"@";
			break;
			case 'M': strEncrypted+="1jdhs12" +"@";
			break;
			case 'm': strEncrypted+="ks3Ssdf" +"@";
			break;
			case 'N': strEncrypted+="refdeft" +"@";
			break;
			case 'n': strEncrypted+="SDesfSf" +"@";
			break;
			case 'O': strEncrypted+="EWskgeG" +"@";
			break;
			case 'o': strEncrypted+="KsdfDeD" +"@";
			break;
			case 'P': strEncrypted+="OdEisEA" +"@";
			break;
			case 'p': strEncrypted+="OeiWSjB" +"@";
			break;
			case 'Q': strEncrypted+="QdisEDs" +"@";
			break;
			case 'q': strEncrypted+="IweFeSe" +"@";
			break;
			case 'R': strEncrypted+="OsdfEsS" +"@";
			break;
			case 'r': strEncrypted+="VdsSvEU" +"@";
			break;
			case 'S': strEncrypted+="PweDiJe" +"@";
			break;
			case 's': strEncrypted+="GrSjEED" +"@";
			break;
			case 'T': strEncrypted+="EWOfsDu" +"@";
			break;
			case 't': strEncrypted+="DbgJeDe" +"@";
			break;
			case 'U': strEncrypted+="OWhUdeE" +"@";
			break;
			case 'u': strEncrypted+="OsdfEDi" +"@";
			break;
			case 'V': strEncrypted+="OBjFeis" +"@";
			break;
			case 'v': strEncrypted+="OsDuFEF" +"@";
			break;
			case 'W': strEncrypted+="NsvFJSS" +"@";
			break;
			case 'w': strEncrypted+="OWEkEEL" +"@";
			break;
			case 'X': strEncrypted+="WOosDJB" +"@";
			break;
			case 'x': strEncrypted+="ONfEJSs" +"@";
			break;
			case 'Y': strEncrypted+="BuFjSlE" +"@";
			break;
			case 'y': strEncrypted+="OPeJ1Ses" +"@";
			break;
			case 'Z': strEncrypted+="Bus8Sj3EK" +"@";
			break;
			case 'z': strEncrypted+="sIeJSF3W" +"@";
			break;
			case '0': strEncrypted+="3Ee29JFx" +"@";
			break;
			case '1': strEncrypted+="0sE98YJ3" +"@";
			break;
			case '2': strEncrypted+="vkIhsYE2" +"@";
			break;
			case '3': strEncrypted+="K8kDK3ds" +"@";
			break;
			case '4': strEncrypted+="P0eKjU3D" +"@";
			break;
			case '5': strEncrypted+="O3oF5F3d" +"@";
			break;
			case '6': strEncrypted+="Kd4IjjkK" +"@";
			break;
			case '7': strEncrypted+="0K4fdk43" +"@";
			break;
			case '8': strEncrypted+="kf4kODeE" +"@";
			break;
			case '9': strEncrypted+="jI3dfeJJ" +"@";
			break;
			case '!': strEncrypted+="dEdSzFaa" +"@";
			break;
			case '@': strEncrypted+="HfgBFjDR" +"@";
			break;
			case '#': strEncrypted+="OD0j43DF" +"@";
			break;
			case '$': strEncrypted+="JF4ifuuj" +"@";
			break;
			case '%': strEncrypted+="B2398JDF" +"@";
			break;
			case '^': strEncrypted+="SDOFowowo3" +"@";
			break;
			case '&': strEncrypted+="kfsd3923" +"@";
			break;
			case '*': strEncrypted+="5452278" +"@";
			break;
			case '(': strEncrypted+="sa39dsdn" +"@";
			break;
			case ')': strEncrypted+="9sd38ksk" +"@";
			break;
			case '-': strEncrypted+="ajsfd564" +"@";
			break;
			case '_': strEncrypted+="SksdkfjE3" +"@";
			break;
			case '=': strEncrypted+="PfeI43Kd" +"@";
			break;
			case '+': strEncrypted+="sISwJ34Dbb" +"@";
			break;
			case '[': strEncrypted+="is8sBh3I" +"@";
			break;
			case '{': strEncrypted+="g9Fj3JsZ" +"@";
			break;
			case ']': strEncrypted+="9jJeU3F3" +"@";
			break;
			case '}': strEncrypted+="9Isk3KbnV" +"@";
			break;
			case ':': strEncrypted+="if3si" +"@";
			break;
			case '|': strEncrypted+="k3JdfiE" +"@";
			break;
			case ';': strEncrypted+="SD3badodZ" +"@";
			break;
			case '"': strEncrypted+="i8d7eHsJA" +"@";
			break;
			case ',': strEncrypted+="pw9Jn3Daa" +"@";
			break;
			case '<': strEncrypted+="vna3L2WEfs" +"@";
			break;
			case '>': strEncrypted+="bIjs32JAesw" +"@";
			break;
			case '.': strEncrypted+="239492r" +"@";
			break;
			case '?': strEncrypted+="asoe3so3" +"@";
			break;
			case '/': strEncrypted+="23k2323" +"@";
			break;
			case '`': strEncrypted+="ks3l76JJA" +"@";
			break;
			case '~': strEncrypted+="Ue83Ijw1223" +"@";
			break;
			}
		}
		return strEncrypted;
	}
	public static String Decrypt(String strEncrypted){
		String strDecrypted="";
		int intCtr=0;
		ArrayList<String> arrlist = new ArrayList<String>();
		String strPattern="([^@])+";
		Pattern ptrPattern=Pattern.compile(strPattern);
		Matcher mtrMatcher =ptrPattern.matcher(strEncrypted);
		while(mtrMatcher.find()){
			arrlist.add(intCtr,mtrMatcher.group());
			intCtr++;
		}
		String[] strArray = new String[arrlist.size()];
		for(intCtr=0;intCtr<arrlist.size();intCtr++){
			strArray[intCtr]="";
			strArray[intCtr]=arrlist.get(intCtr);
			switch(strArray[intCtr]){
			case "XyZdjfd": strDecrypted+="A";
			break;
			case "yJdEwHr": strDecrypted+="a";
			break;
			case "1ayFBs2*": strDecrypted+="B";
			break;
			case "xYd0221": strDecrypted+="b";
			break;
			case "3fjks32": strDecrypted+="C";
			break;
			case "fsjkhfj": strDecrypted+="c";
			break;
			case "atsd7f66f": strDecrypted+="D";
			break;
			case "dhfjshfjdf": strDecrypted+="d";
			break;
			case "we67r5f62": strDecrypted+="E";
			break;
			case " 627s": strDecrypted+="e";
			break;
			case "23yu23a": strDecrypted+="F";
			break;
			case "fjsdhf7": strDecrypted+="f";
			break;
			case "2ui2u4": strDecrypted+="G";
			break;
			case "asdsd21": strDecrypted+="g";
			break;
			case "fuef62": strDecrypted+="H";
			break;
			case "4376fda": strDecrypted+="h";
			break;
			case "djhs5AS": strDecrypted+="I";
			break;
			case "dgshdg25": strDecrypted+="i";
			break;
			case "xtte212": strDecrypted+="J";
			break;
			case "y23sjoHr": strDecrypted+="j";
			break;
			case "23241": strDecrypted+="K";
			break;
			case "dhs621": strDecrypted+="k";
			break;
			case "dhsd623": strDecrypted+="L";
			break;
			case "dshdhs2": strDecrypted+="l";
			break;
			case "1jdhs12": strDecrypted+="M";
			break;
			case "ks3Ssdf": strDecrypted+="m";
			break;
			case "refdeft": strDecrypted+="N";
			break;
			case "SDesfSf": strDecrypted+="n";
			break;
			case "EWskgeG": strDecrypted+="O";
			break;
			case "KsdfDeD": strDecrypted+="o";
			break;
			case "OdEisEA": strDecrypted+="P";
			break;
			case "OeiWSjB": strDecrypted+="p";
			break;
			case "QdisEDs": strDecrypted+="Q";
			break;
			case "IweFeSe": strDecrypted+="q";
			break;
			case "OsdfEsS": strDecrypted+="R";
			break;
			case "VdsSvEU": strDecrypted+="r";
			break;
			case "PweDiJe": strDecrypted+="S";
			break;
			case "GrSjEED": strDecrypted+="s";
			break;
			case "EWOfsDu": strDecrypted+="T";
			break;
			case "DbgJeDe": strDecrypted+="t";
			break;
			case "OWhUdeE": strDecrypted+="U";
			break;
			case "OsdfEDi": strDecrypted+="u";
			break;
			case "OBjFeis": strDecrypted+="V";
			break;
			case "OsDuFEF": strDecrypted+="v";
			break;
			case "NsvFJSS": strDecrypted+="W";
			break;
			case "OWEkEEL": strDecrypted+="w";
			break;
			case "WOosDJB": strDecrypted+="X";
			break;
			case "ONfEJSs": strDecrypted+="x";
			break;
			case "BuFjSlE": strDecrypted+="Y";
			break;
			case "OPeJ1Ses": strDecrypted+="y";
			break;
			case "Bus8Sj3EK": strDecrypted+="Z";
			break;
			case "sIeJSF3W": strDecrypted+="z";
			break;
			case "3Ee29JFx": strDecrypted+="0";
			break;
			case "0sE98YJ3": strDecrypted+="1";
			break;
			case "vkIhsYE2": strDecrypted+="2";
			break;
			case "K8kDK3ds": strDecrypted+="3";
			break;
			case "P0eKjU3D": strDecrypted+="4";
			break;
			case "O3oF5F3d": strDecrypted+="5";
			break;
			case "Kd4IjjkK": strDecrypted+="6";
			break;
			case "0K4fdk43": strDecrypted+="7";
			break;
			case "kf4kODeE": strDecrypted+="8";
			break;
			case "jI3dfeJJ": strDecrypted+="9";
			break;
			case "dEdSzFaa": strDecrypted+="!";
			break;
			case "HfgBFjDR": strDecrypted+="@";
			break;
			case "OD0j43DF": strDecrypted+="#";
			break;
			case "JF4ifuuj": strDecrypted+="$";
			break;
			case "B2398JDF": strDecrypted+="%";
			break;
			case "SDOFowowo3": strDecrypted+="^";
			break;
			case "kfsd3923": strDecrypted+="&";
			break;
			case "5452278": strDecrypted+="*";
			break;
			case "sa39dsdn": strDecrypted+="(";
			break;
			case "9sd38ksk": strDecrypted+=")";
			break;
			case "ajsfd564": strDecrypted+="-";
			break;
			case "SksdkfjE3": strDecrypted+="_";
			break;
			case "PfeI43Kd": strDecrypted+="=";
			break;
			case "sISwJ34Dbb": strDecrypted+="+";
			break;
			case "is8sBh3I": strDecrypted+="[";
			break;
			case "g9Fj3JsZ": strDecrypted+="{";
			break;
			case "9jJeU3F3": strDecrypted+="]";
			break;
			case "9Isk3KbnV": strDecrypted+="}";
			break;
			case "if3si": strDecrypted+=":";
			break;
			case "k3JdfiE": strDecrypted+="|";
			break;
			case "SD3badodZ": strDecrypted+=";";
			break;
			case "pw9Jn3Daa": strDecrypted+=",";
			break;
			case "vna3L2WEfs": strDecrypted+="<";
			break;
			case "bIjs32JAesw": strDecrypted+=">";
			break;
			case "239492r": strDecrypted+=".";
			break;
			case "asoe3so3": strDecrypted+="?";
			break;
			case "23k2323": strDecrypted+="/";
			break;
			case "ks3l76JJA": strDecrypted+="`";
			break;
			case "Ue83Ijw1223": strDecrypted+="~";
			break;
			
			}
		}
		return strDecrypted;
	}
	public static void main(String args[]){
		String strMessage="sample";
		strMessage=Encrypt(strMessage);
		System.out.println(strMessage);
		strMessage=Decrypt(strMessage);
		System.out.println(strMessage);
	}
}

